### PR TITLE
feature: additional syntax for define Macro, using LabeledStatement, …

### PR DESCRIPTION
**Pull request by Gvozd**
I think this additioan syntax more hygienic
- it's worked without transform (may used for debuging)
- also this syntax correct wor linting

``` javascript
macro: {
  var FOO = function() {
    return "foo";
  };
}
macro: var FOO1 = function() {
  return "foo1";
};
```

@phpnode , what yout think about this feature?
If this good idea, I will continue this work

### CODE REVIEW

**Comment by phpnode** [comment]
@Gvozd like it! I had very similar thoughts recently. It should also allow function declarations:

```js
macro: function FOO () {}
```

**Comment by Gvozd** [comment]
for full hygienic, FunctionDeclaration in strict mode has limitations, like in native JS
```javascript
(function () {
  'use strict';
  //Uncaught SyntaxError: In strict mode code, functions can only be declared at top level or immediately within another function
  macro: function FOO() {}
})();

(function () {
  'use strict';
  macro: {function FOO() {}}
  console.log(typeof FOO);//undefined because scoping
})();
```

But I planned support FD also
Once you agree, I will continue to work

**Comment by phpnode** [comment]
@Gvozd this looks really great. The limitation for function declarations is a bit unfortunate but I think it's the much more natural syntax, so we should probably allow it. I can merge this now or wait if you want to work on that too? Up to you, thanks again for all your hard work on this library, you've improved it vastly.

**Comment by Gvozd** [comment]
No, not merge this PR - I not ended work
I create this PR for discussing with you, and show proto of code if you want
In few days I return to this feature, and ended work

I myself merge code, when when it is ready

**Comment by Gvozd** [comment]
OK, I allow all variants of FunctionDeclaration, but with warning notice.

I am happy to to work on this plugin)
This is a new experience for me
And I plan to use it in my library for quick search in JSON objects
Coming soon it)

**Comment by Gvozd** [comment]
Done
Actually merged to master

**Pull request merged**
