### PR TITLE
update version&api of babel

### PR DESCRIPTION
**Pull request by Gvozd**
Now the library works correctly with the latest actual babel.
Actually fixed https://github.com/codemix/babel-plugin-macros/issues/2 & any other problems with current babel.

Also I added a few tests.

### CODE REVIEW

**Comment by Gvozd** [comment]
Sorry, this pull request not yet ready.
I found&fix some problems.
Tests also does not work in travis-ci

I'm in proccess for gren travis-ci

**Comment by phpnode** [comment]
@Gvozd  oh wow! this is awesome work!

**Comment by phpnode** [comment]
@Gvozd I'd be happy with removing support for older node versions to be honest. I think it's fine at this point. Feel free to update `.travis.yml`

**Comment by Gvozd** [comment]
Thanks

I have some question - may be you know?
Travis show me build log only for first build in PR
In build https://travis-ci.org/codemix/babel-plugin-macros/builds/103726842 i don't see any console log's
You also don't see this logs, or maybe only my trouble?

**Comment by phpnode** [comment]
Thanks so much for this. I just published 1.0.0 to npm and added you as a collaborator.

I don't see any logs either, it's possibly a travis problem or maybe they stopped supporting old nodes (though that seems unlikely).

**Comment by Gvozd** [comment]
i don't see any logs
in my link tested only actual nodes, but has no logs
i think it some travis-ci temp problem(it seemd logs sended to amazon, but some went wrong)


but we has another, more actually problem
you removed /lib/ in new npm package
i did `npm i babel-plugin-macros` and lib/ actually has no)
some wrong on publish package?

**Comment by phpnode** [comment]
@Gvozd oops! I just published 1.0.1 which seems to have fixed the issue (npm uses `.gitignore` by default if there's no `.npmignore`).

**Pull request merged**
