### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by Gvozd**
- refactoring. split code to multiple files  
  @phpnode , what you think about new project structure?
- fix some bugs
  *\* temp locked FunctionDeclaration in macoBody, because wrong renames
  *\* fix "Maximum call stack size exceeded" if used blocks in macro
- optimize travis-ci time from 50-120sec to 40sec  
  i cached node_modules
- some mor tests

### CODE REVIEW

**Comment by phpnode** [comment]
@Gvozd looks a lot nicer but it'll be a day or two before I can do a proper read through of this

**Comment by Gvozd** [comment]
Of course
I want you to look carefully the changes
The project must be well-read not only for me)
And also, I could avoid missteps within refactoring

Also i refactor logic of main visitor
I split it to collectMacros, and processMacros visitors
This allowed to remove the state, and simplified logic

**Comment by Gvozd** [comment]
image

**Comment by Gvozd** [comment]
@phpnode , maybe you look it at this weekend?

**Comment by phpnode** [comment]
@Gvozd sorry, busy week! Looking now

**Comment by phpnode** [comment]
@Gvozd very nice work.

**Pull request merged**
